Sprint 07
tsomuk/MovieQuiz_yp pull request #5
Opened 2023-06-26 04:34 UTC by tsomuk

2023-06-26 20:35 UTC, mmbabaev requested changes

2023-06-26 20:35 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    func isLastQuestion() -> Bool {
можно сделать это computed property

2023-06-26 20:35 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    func isLastQuestion() -> Bool {
через var

2023-06-26 20:35 UTC, mmbabaev commented on MovieQuizTests/MovieQuizPresenterTests.swift
> +        let viewModel = sut.convert(model: question)
Если есть желание, предлагаю немного улучшить тест:

1) Вообще функция convert может быть приватной, она не используется в vc
2) Тогда нужно можно проверить ее косвенно. Проверим метод `didReceiveNextQuestion` 
3) Нужно проверить, что vc получил ожидаемую viewModel. Для этого в моке `func show(quiz step: QuizStepViewModel)` нужно сохранять step в отдельное свойство
4) В тесте вызываем `didReceiveNextQuestion`, затем достаем `viewModel` из мок vc, проверяем его

2023-06-26 20:35 UTC, mmbabaev commented on MovieQuizTests/MoviesLoaderTests.swift
> +                XCTAssertEqual(movies.items.count, 2)
тут можно дополнительно проверить свойства элементов в массиве

2023-06-26 20:35 UTC, mmbabaev commented
Есть упавшие тесты
<img width="257" alt="Screenshot 2023-06-26 at 23 35 11" src="https://github.com/tsomuk/MovieQuiz/assets/12600807/ccad390a-13e9-4d81-8ff6-9a77c7f4f926">

2023-06-27 09:01 UTC, tsomuk commented on MovieQuizTests/MovieQuizPresenterTests.swift
> +        let viewModel = sut.convert(model: question)
Спасибо за замечания, попробую это реализоваться после ЖД, который уже послезавтра =)

2023-06-28 12:05 UTC, merged